title: Jack Haydock
author: Jack Haydock
description: A portfolio of the assorted works of a sad and lonely man

highlighter: null
permalink: /posts/:year/:title

url: "http://www.jackhaydock.co.uk" 
baseurl: ""

sass:
  sass_dir: public/css
  style: :compressed
